name: Tests

on: [ push ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        php: [ "7.4", "8.0", "8.1" ]

    name: "PHP ${{ matrix.php }}"

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --prefer-stable

      - name: Execute tests
        run: vendor/bin/phpunit
